name: Deploy website
on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - run: npm install
    - run: npm run build

    - name: Is a tag created auto?
      id: create_tag
      uses: jaywcjlove/create-tag-action@v1.3.5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        package-path: ./package.json

    - name: Generate Changelog
      id: changelog
      uses: jaywcjlove/changelog-generator@v1.4.8
      if: steps.create_tag.outputs.successful
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        head-ref: ${{ steps.create_tag.outputs.version }}
        filter-author: (jaywcjlove|小弟调调™|dependabot\[bot\]|Renovate Bot)
        filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

    - name: Create Release
      uses: jaywcjlove/create-tag-action@v1.3.5
      with:
        package-path: ./package.json
        release: true
        body: |
          [![](https://img.shields.io/badge/Open%20in-unpkg-blue)](https://uiwjs.github.io/npm-unpkg/#/pkg/dev-site@${{steps.changelog.outputs.version}}/file/README.md) [![npm version](https://img.shields.io/npm/v/dev-site.svg)](https://www.npmjs.com/package/dev-site) [![npm bundle size](https://img.shields.io/bundlephobia/minzip/dev-site)](https://bundlephobia.com/result?p=dev-site@${{steps.changelog.outputs.version}})
          
          ```bash
          npm i dev-site@${{steps.changelog.outputs.version}}
          ```

          ${{ steps.changelog.outputs.compareurl }}
          
          ${{ steps.changelog.outputs.changelog }}

    - name: 📦  dev-site publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
        package: ./package.json

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build